CREATE SCHEMA RESTAURANT;

CREATE TABLE RESTAURANT.INGREDIENT (
    id UUID PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE RESTAURANT.RECIPE (
    id UUID PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE RESTAURANT.RECIPE_ITEM (
    id UUID PRIMARY KEY NOT NULL,
    recipe_id UUID NOT NULL,
    ingredient_id UUID NOT NULL,
    measure VARCHAR(20) NOT NULL,
    amount INT
);

CREATE TABLE RESTAURANT.RECIPE_STEP (
    id UUID PRIMARY KEY,
    recipe_id UUID NOT NULL,
    step VARCHAR(100) NOT NULL,
    position INT NOT NULL
);



